### ISSUE TITLE
Be able to change output to

### ISSUE THREAD

**Issue by phpandrew** [musicbeeremote/android-app#172]
Currently have sonos setup, but by default MusicBee plays from PC speakers.
Using Play More > Output to > Sonos works, but would be nice to be able to control this through the app as well.

**Comment by kelsos** [comment]
@lylesback2 This is already implemented on the plugin side and there has already been some work on the application.

https://github.com/musicbeeremote/android-app/blob/3d74562744f92b5c7ec0e4b53551281d72cc1e25/app/src/main/java/com/kelsos/mbrc/ui/dialogs/OutputSelectionDialog.kt#L24

It will definitely be in the next update.

**Comment by kelsos** [comment]
Closing the issue. v1.3.0 is pending for approval and it will be available in the next couple of days
