### ISSUE TITLE
Please provide FOSS version

### ISSUE THREAD

**Issue by IzzySoft** [musicbeeremote/android-app#207]
The latest release adds a.o. Crashlytics, Firebase Analytics and, as dependency of the two, Google Mobile Services and Firebase. Thus the app is no longer fully FOSS, as those services/libraries are proprietary. For most users explicitly setting on "personal solutions" using their own (usually self-hosted) services instead of cloud-based ones, this is a no-go.

Can you please provide a version (including its APK attached to releases) that comes without those trackers? Thanks in advance!

**Comment by kelsos** [comment]
Hey @IzzySoft, the plan was to have this pre-release out for a week or two, to test for the application stability, get some metrics, fix any crashes and then create one version with the trackers and one without as I was doing with previous all the previous releases and publish that as a release. 

I can easily provide a version without the trackers but keep in mind that this is a pre-release version and there might be issues. A

**Comment by kelsos** [comment]
I updated the release to include the tracker free version https://github.com/musicbeeremote/android-app/releases/tag/v1.2.0-beta1

**Comment by kelsos** [comment]
Btw I would suggest to not list this version as the latest, at least until the final 1.2.0 release is tagged. This version is tagged as a pre-release because like I mentioned above there might be some stability issues.

**Comment by IzzySoft** [comment]
> keep in mind that this is a pre-release version and there might be issues.

Ugh… now that you mention it, I wonder why my updater pulled that at all. Default is to skip pre-releases – and I have not set it explicitly for your app. Apologies!

> Btw I would suggest to not list this version as the latest

Agreed, but other than at F-Droid.org I do not set the "recommended version" explicitly (I run a "binary repo", so no builds, and setting that happens on build time IIRC).

So if the release is already at the horizon, I'd suggest I simply remove the beta (and the corresponding AntiFeatures), explicitly force-set to skip pre-releases, and hope the updater honors this but still fetches the release when it's there. What do you think? Of course I could alternatively replace the APK (instead of removing it; just done that now "interim"), with the other steps (skipping pre-releases) of course applied. Just let me know.

**Comment by kelsos** [comment]
It sounds good to me. 

Also it would be better if you could also check the apk name somehow. I have two flavors for the application and the foss one is always named `com.kelsos.mbrc-github-release-v...apk`. This doesn't include any crashlytics, play services or analytics. The version that includes the non free libraries and goes to play store is named`com.kelsos.mbrc-play-release-v...apk`.

**Comment by IzzySoft** [comment]
> It sounds good to me.

Thanks! Then I'll leave it at that.

> Also, it would be better if you could check the apk name somehow.

You mean the following fragment in my configuration for your app?

```yaml
ApkMatch: /mbrc-github-/
```

Yupp, that's done already :smiley: Just fixed it today (before it was `/github/` which unfortunately also matches the host name (`github.com`). Initially I grabbed APKs via site scraping, so the match was applied on the app name only – need to check the other `ApkMatch` entries as well for such lapses, as I'm now using Github API for 2+ years which has the full URL in place. MusicBee is already in my repo a little longer, was added in 12/2017…

Thanks for thinking of that as well!

**Comment by kelsos** [comment]
hey @IzzySoft I pushed 2 versions out, but it doesn't seem that they were picked up beta1 is still listed as the latest.

**Comment by IzzySoft** [comment]
That's funny. I've just now triggered an update manually (not picking the APK manually, but told my updater to check if there is something to update to) – and it is fetching an APK. Which raises the question…

Ugh, exactly: updater is still set to "Static" (i.e. check once a month, as opposed to daily). Apologies – fixed now. Next sync in about 2h, as usual. Thanks for the wake-up call!

**Comment by kelsos** [comment]
> That's funny. I've just now triggered an update manually (not picking the APK manually, but told my updater to check if there is something to update to) – and it is fetching an APK. Which raises the question…
> 
> Ugh, exactly: updater is still set to "Static" (i.e. check once a month, as opposed to daily). Apologies – fixed now. Next sync in about 2h, as usual. Thanks for the wake-up call!

No worries, I just checked after the release to make sure it is updated :)
